---
title: "Recalculating CON and CW without Penalty"
output: html_document
---

```{r setup, results = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(httr)
dir <- here::here("baltic2015")
## create layers directory
if(!file.exists(file.path(dir, "layers"))){dir.create(file.path(dir, "layers"))}
```


**revised FIS data, original v2015 Pressures/Resilinece Layers**

```{r get v2015 layers from  bhi archive, eval = FALSE}
## base score calculation on v2015 layers
lyrcsv2015 <- read_csv(file.path(dir, "compare", "layers2015.csv"))

## get layers from github
req <- GET("https://api.github.com/repos/OHI-Science/bhi-1.0-archive/git/trees/draft?recursive=1")
stop_for_status(req)

filelist <- unlist(lapply(content(req)$tree, "[", "path"), use.names = FALSE) %>% 
  grep(pattern = "baltic2015/layers/", value = TRUE) %>% 
  str_extract("/[a-zA-Z0-9_-]+.csv|/[a-zA-Z0-9_-]+$") %>% 
  str_remove_all(".csv")

lapply(
  c(
    intersect(lyrcsv2015$filename, str_remove(filelist, "/") %>% paste0(".csv")), 
    "eco_trend_scores_BHI2015.csv" # random capitalization causes issue...
  ),
  function(x){
    read_csv(paste0("https://raw.githubusercontent.com/OHI-Science/bhi-1.0-archive/draft/baltic2015/layers/", unlist(x))) %>% 
      write_csv(file.path(dir, "layers", unlist(x) %>% str_replace_all("_BHI2015", "_bhi2015")))
  }
)
```

```{r get new FIS layers, eval = FALSE}
## get new revised FIS layers in the bhi-prep github repository
req <- GET("https://api.github.com/repos/OHI-Science/bhi-prep/git/trees/master?recursive=1")
stop_for_status(req)
filelist <- unlist(lapply(content(req)$tree, "[", "path"), use.names = FALSE) %>% 
  grep(pattern = "layers/v2019/", value = TRUE) %>% 
  str_extract("[a-z0-9_]+.csv")
lapply(
  filelist,
  function(x){
    read_csv(paste0("https://raw.githubusercontent.com/OHI-Science/bhi-prep/master/layers/v2019/", unlist(x))) %>% 
      rename(rgn_id = region_id) %>% 
      write_csv(file.path(dir, "layers", unlist(x)))
  }
)
new_fis_lyrs <- c("fis_ffmsy_bhi2019.csv", "fis_bbmsy_bhi2019.csv", "fis_landings_bhi2019.csv")
file.exists(file.path(dir, "layers", new_fis_lyrs))
```

```{r configure layerscsv and functionsR, results = FALSE, message = FALSE, warning = FALSE}

## create extra entry for the cod penalty layer
cod_penalty_lyr <- data.frame(
  targets = "FIS", layer = "fis_cod_penalty", name = "Cod Condition Penalty Factor", 
  description = "Proportion of Cod 20-40cm with Fultons K less than 0.8", 
  fld_value = "penalty_factor", units = "proportion", 
  filename = "fis_cod_penalty_bhi2019.csv", clip_n_ship_disag = NA, clip_n_ship_disag_description = NA, 
  layer_gl = NA, path_in = NA, rgns_in = NA, fld_id_num = "rgn_id", fld_id_chr = NA, 
  fld_category = NA, fld_year = NA, fld_val_num = "penalty_factor", fld_val_chr = NA, 
  file_exists = NA, year_min = NA, year_max = NA, 
  val_min = NA, val_max = NA, val_0to1 = NA, flds_unused = NA, 
  flds_missing = NA, rows_duplicated = NA, num_ids_unique = NA, data_na = NA
)

## reconfigure layers.csv file to use new/revised FIS layers, and including cod penalty factor
lyrs_csv_fis2019 <- rbind(
  read_csv(file.path(dir, "compare", "layers2015.csv")) %>%
  mutate(
    filename = ifelse(
      layer == "fis_bbmsy", "fis_bbmsy_bhi2019.csv",
      ifelse(layer == "fis_ffmsy", "fis_ffmsy_bhi2019.csv",
             ifelse(layer == "fis_landings", "fis_landings_bhi2019.csv", filename)
      )
    ),
    fld_val_num = ifelse(
      layer == "fis_bbmsy", "value",
      ifelse(layer == "fis_ffmsy", "value", fld_val_num)
    ),
    fld_value = ifelse(
      layer == "fis_bbmsy", "value",
      ifelse(layer == "fis_ffmsy", "value", fld_value)
    )),
  cod_penalty_lyr
)
write_csv(lyrs_csv_fis2019, file.path(dir, "layers.csv"))

## v2019 functions.R with revised FIS and CON functions
## FIS function revised so F-scores piecewise eqn aligns better were slope and line segments meet
## CON function revised to calculate scores without penalty factor
file.copy(file.path(dir, "compare", "functions2019_cwNew.R"), file.path(dir, "conf", "functions.R"), overwrite = TRUE)
```

**Using a revised functions.R file (`compare/functions2019_cwNew.R`) with updated FIS and CON goal functions**

```{r recalculate scores, results = FALSE, message = FALSE, warning = FALSE}
source(file.path(dir, "calculate_scores.R"))
scores_noCONpenalty <- read.csv(file.path(dir, "scores.csv"))
```

**Compare to CON scores with Penalty**

```{r compare to scores calcualted with CON penalty, results = FALSE, message = FALSE, warning = FALSE}
file.copy(file.path(dir, "compare", "functions2019.R"), file.path(dir, "conf", "functions.R"), overwrite = TRUE)
source(file.path(dir, "calculate_scores.R"))
scoresOriginal <- read.csv(file.path(dir, "scores.csv")) %>% rename(scores_original = score)

compareScores <- left_join(scores_noCONpenalty, scoresOriginal, by = c("goal", "dimension", "region_id")) %>% 
  mutate(diffs = score - scores_original)
```

```{r visualize comparision}
ggplot(compareScores %>%
         filter(region_id %in% 0:42) %>% 
         filter(goal %in% c("CON", "CW",  "Index")) %>% 
         filter(dimension %in% c("score", "status", "future"))) +
  geom_col(aes(x = region_id, y = diffs), width = 0.7) +
  facet_grid(vars(dimension), vars(goal))

tmpplot <- ggplot(compareScores %>%
                    filter(region_id %in% 0:42) %>% 
                    filter(goal %in% c("CON", "CW",  "Index")) %>% 
                    filter(dimension %in% c("score", "status", "future"))) +
  geom_col(aes(x = region_id, y = score), width = 0.7) +
  facet_grid(vars(dimension), vars(goal))
plotly::ggplotly(tmpplot)
```




