---
title: "Regions"
output: html_document
---

---

```{r setup, echo = F, warning = FALSE, message = F}
source("_site.R")
```

Regions are the fundamental spatial units of analysis for the Ocean Health Index. Scores are calculated for each region individually and then combined (with an offshore area-weighted average) to produce scores for the entire Baltic Sea.  

**There are 42 BHI regions in the Baltic Sea.**


```{r, eval = FALSE}

## dir_scenario_gh defined in _site.R
if (!"geojson" %in% names(config)) stop(sprintf("missing geojson path variable in %s/conf/config.R", dir_scenario_gh))

geojson <- normalizePath(file.path(dir_scenario_gh, config$geojson))

## read spatial (can simplify with R package rmapshaper)
if (!file.exists(geojson)) stop(sprintf("GeoJSON file specified in %s/conf/config.R not found: %s", dir_scenario_gh, geojson))
cat(file = stderr(), "read rgns from geojson\n")
rgns <- geojsonio::geojson_read(geojson, what = "sp")
if ("rgn_nam" %in% names(rgns@data) & !"rgn_name" %in% names(rgns@data)) rgns@data = rgns@data %>% mutate(rgn_name = rgn_nam)

## get bbox to shrink
bbox_shrink = function(p, pct){
  b = bbox(p)
  dx = (b[3] - b[1]) * (pct/100)
  dy = (b[4] - b[2]) * (pct/100)
  c(b[1] + dx, b[2] + dy, b[3] - dx, b[4] - dy)
}
b = bbox_shrink(rgns, map_shrink_pct)

leaflet() %>%
  addProviderTiles("Stamen.TonerLite") %>%
  addPolygons(
    data = rgns, 
    layerId = ~rgn_id,
    label = mapply(function(n) {
      HTML(sprintf("<em>%s</em>", htmlEscape(n)))},
      rgns$rgn_name, SIMPLIFY = F),
    stroke = TRUE, opacity = 0.5, weight = 2, fillOpacity = 0.5, smoothFactor = 0.5,
    color = ~colorNumeric('Purple', rgns$rgn_id)(rgn_id)) %>%
  fitBounds(lng1 = b[1], lat1 = b[2], lng2 = b[3], lat2 = b[4]) %>%
  htmlwidgets::onRender("
  function(el, t) {
    var defaultStyle = {
      // stroke, ie polygon border
        opacity:     0.5,
        weight:      2,
      // fill, ie polygon interior
        fillOpacity: 0.5,
    };
    var highlightStyle = {
      // stroke, ie polygon border
        opacity:     0.9,
        weight:      6,
      // fill, ie polygon interior
        fillOpacity: 0.9,
    };
    var myMap = this;
    var layers = myMap._layers;
    for(var i in layers) {
      var layer = layers[i];
      if(layer.label) {
        layer.on('mouseover',
          function(e) {
            this.setStyle(highlightStyle);
            // this.bringToFront();
        });
        layer.on('mouseout',
          function(e) {
            this.setStyle(defaultStyle);
            // this.bringToBack();
        });
      }
    }
  }")
```
